# ITMGT 25.03 EE
# Assignment 3A

This is a data-cleaning assignment and is the first of two parts. The second part (3B) will be given Monday or Tuesday next week. This notebook is uploaded to our Github repository along with a csv of fake, dirty data called **recweekdata.csv**.


The output of this assignment is to convert recweekdata.csv into processable data for statistics. Submit the following files through GitHub:
1. A cleaned recweekdata.csv called cleanrecweekdata.csv **(5 points)**
2. This notebook, containing the code (properly commented) that you used to clean the data **(5 points)**
3. An html file of summary statistics from each column called **stats.html**. The requirements for the summary statistics are described below. **(10 points)**

This entire assignment (3A) is worth 20 points.

Upload your output files to your Github repositories. Make sure to send an email to **joben.ilagan@gmail.com** once you're done.

This assignment is due on **Tuesday, July 9, 2019** at 12:00NN.

In [1]:
# extracting dirty list of courses 

import csv

dirty_course_list = list()

with open('recweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            dirty_course_list.append(row[5])
        line_count += 1
        
dirty_course_list

['BS LM',
 'Management',
 'BS CTM',
 'BS ITE',
 'BS CTM',
 'Management',
 'BS LM',
 'Management Engineering',
 'Management Engineering',
 'CTM',
 'BS LM',
 'BS ME',
 'BS CTM',
 'BS MGT',
 'Information Technology Entrepreneurship',
 'BS LM',
 'Information Technology Entrepreneurship',
 'BS MGT',
 'Information Technology Entrepreneurship',
 'BS ME',
 'LM',
 'ITE',
 'MGT',
 'ME',
 'BS ME',
 'BS ME',
 'CTM',
 'BS LM',
 'LM',
 'Communications Technology',
 'BS ITE',
 'Management',
 'BS ITE',
 'BS LM',
 'ITE',
 'BS MGT',
 'MGT',
 'Legal Management',
 'ME',
 'BS LM',
 'BS MGT',
 'BS LM',
 'Management',
 'Information Technology Entrepreneurship',
 'Management Engineering',
 'ME',
 'Management',
 'Information Technology Entrepreneurship',
 'Legal Management',
 'BS LM',
 'ITE',
 'Communications Technology',
 'BS MGT',
 'BS CTM',
 'Management Engineering',
 'ME',
 'BS CTM',
 'BS ME',
 'Information Technology Entrepreneurship',
 'ITE',
 'Communications Technology',
 'ITE',
 'BS ME',
 'Information 

In [2]:
# identifying unique course names

unique_courses = set(dirty_course_list)

unique_courses

{'BS CTM',
 'BS ITE',
 'BS LM',
 'BS ME',
 'BS MGT',
 'CTM',
 'Communications Technology',
 'ITE',
 'Information Technology Entrepreneurship',
 'LM',
 'Legal Management',
 'ME',
 'MGT',
 'Management',
 'Management Engineering'}

In [3]:
# making course dictionary

unique_courses_dictionary = {course:None for course in unique_courses}

unique_courses_dictionary

{'Communications Technology': None,
 'BS MGT': None,
 'Legal Management': None,
 'ME': None,
 'BS CTM': None,
 'MGT': None,
 'LM': None,
 'Management': None,
 'BS ITE': None,
 'BS LM': None,
 'BS ME': None,
 'ITE': None,
 'Management Engineering': None,
 'Information Technology Entrepreneurship': None,
 'CTM': None}

In [5]:
# changing dirty course names to proper/clean course names

for i in unique_courses_dictionary:
    final_course = input(i + ": " + "Enter name: ")
    unique_courses_dictionary[i] = final_course

Communications Technology: Enter name: BS Communications Technology Management
BS MGT: Enter name: BS Management
Legal Management: Enter name: BS Legal Management
ME: Enter name: BS Management Engineering
BS CTM: Enter name: BS Communications Technology Management
MGT: Enter name: BS Management
LM: Enter name: BS Legal Management
Management: Enter name: BS Management
BS ITE: Enter name: BS Information Technology Entrepreneurship
BS LM: Enter name: BS Legal Management
BS ME: Enter name: BS Management Engineering
ITE: Enter name: BS Information Technology Entrepreneurship
Management Engineering: Enter name: BS Management Engineering
Information Technology Entrepreneurship: Enter name: BS Information Technology Entrepreneurship
CTM: Enter name: BS Communications Technology Management


In [6]:
# creating new list for courses with clean course list

import re

clean_course_list = [re.sub(r''.join(course),r''.join(unique_courses_dictionary[course]),course) for course in dirty_course_list]

clean_course_list

['BS Legal Management',
 'BS Management',
 'BS Communications Technology Management',
 'BS Information Technology Entrepreneurship',
 'BS Communications Technology Management',
 'BS Management',
 'BS Legal Management',
 'BS Management Engineering',
 'BS Management Engineering',
 'BS Communications Technology Management',
 'BS Legal Management',
 'BS Management Engineering',
 'BS Communications Technology Management',
 'BS Management',
 'BS Information Technology Entrepreneurship',
 'BS Legal Management',
 'BS Information Technology Entrepreneurship',
 'BS Management',
 'BS Information Technology Entrepreneurship',
 'BS Management Engineering',
 'BS Legal Management',
 'BS Information Technology Entrepreneurship',
 'BS Management',
 'BS Management Engineering',
 'BS Management Engineering',
 'BS Management Engineering',
 'BS Communications Technology Management',
 'BS Legal Management',
 'BS Legal Management',
 'BS Communications Technology Management',
 'BS Information Technology Entre

In [7]:
# extracting dirty list of years

import csv

dirty_year_list = list()

with open('recweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            dirty_year_list.append(row[4])
        line_count += 1
        
dirty_year_list

['1998',
 '2001',
 '1997',
 '97',
 '97',
 '1999',
 '98',
 '99',
 '97',
 '2001',
 '98',
 '97',
 '1999',
 '1999',
 '98',
 '99',
 '97',
 '1997',
 '1997',
 '97',
 '99',
 '1999',
 '97',
 '97',
 '97',
 '1999',
 '1997',
 '2000',
 '1999',
 '1999',
 '99',
 '99',
 '99',
 '1999',
 '2001',
 '1998',
 '2000',
 '2001',
 '1997',
 '1998',
 '99',
 '98',
 '1999',
 '98',
 '97',
 '98',
 '1999',
 '99',
 '97',
 '2001',
 '98',
 '1999',
 '2000',
 '98',
 '1998',
 '1998',
 '2001',
 '97',
 '98',
 '99',
 '98',
 '2000',
 '2000',
 '97',
 '97',
 '1997',
 '1997',
 '2001',
 '1998',
 '98',
 '99',
 '1999',
 '1998',
 '1997',
 '1998',
 '1997',
 '2000',
 '2000',
 '2000',
 '99',
 '97',
 '1997',
 '2000',
 '1999',
 '1999',
 '98',
 '1998',
 '97',
 '1998',
 '99',
 '97',
 '97',
 '1998',
 '97',
 '2001',
 '1999',
 '1997',
 '98',
 '98',
 '99',
 '97',
 '2001',
 '2000',
 '2001',
 '99',
 '97',
 '2001',
 '99',
 '1998',
 '99',
 '2001',
 '97',
 '97',
 '99',
 '98',
 '97',
 '1997',
 '1999',
 '1997',
 '97',
 '2000',
 '2001',
 '1999',
 '1999'

In [9]:
clean_year_list = []

for year in dirty_year_list:
    if len(year) == 2: # example: 97, 98, 99
        clean_year_list.append(year)
    else: # example: 1997, 1998, 1999
        newyear = year[2:]
        clean_year_list.append(newyear)
        
clean_year_list

['98',
 '01',
 '97',
 '97',
 '97',
 '99',
 '98',
 '99',
 '97',
 '01',
 '98',
 '97',
 '99',
 '99',
 '98',
 '99',
 '97',
 '97',
 '97',
 '97',
 '99',
 '99',
 '97',
 '97',
 '97',
 '99',
 '97',
 '00',
 '99',
 '99',
 '99',
 '99',
 '99',
 '99',
 '01',
 '98',
 '00',
 '01',
 '97',
 '98',
 '99',
 '98',
 '99',
 '98',
 '97',
 '98',
 '99',
 '99',
 '97',
 '01',
 '98',
 '99',
 '00',
 '98',
 '98',
 '98',
 '01',
 '97',
 '98',
 '99',
 '98',
 '00',
 '00',
 '97',
 '97',
 '97',
 '97',
 '01',
 '98',
 '98',
 '99',
 '99',
 '98',
 '97',
 '98',
 '97',
 '00',
 '00',
 '00',
 '99',
 '97',
 '97',
 '00',
 '99',
 '99',
 '98',
 '98',
 '97',
 '98',
 '99',
 '97',
 '97',
 '98',
 '97',
 '01',
 '99',
 '97',
 '98',
 '98',
 '99',
 '97',
 '01',
 '00',
 '01',
 '99',
 '97',
 '01',
 '99',
 '98',
 '99',
 '01',
 '97',
 '97',
 '99',
 '98',
 '97',
 '97',
 '99',
 '97',
 '97',
 '00',
 '01',
 '99',
 '99',
 '98',
 '00',
 '00',
 '98',
 '98',
 '00',
 '99',
 '99',
 '99',
 '00',
 '99',
 '00',
 '98',
 '97',
 '99',
 '99',
 '98',
 '99',
 '99',

In [20]:
# extracting dirty list of months

import csv

dirty_month_list = list()

with open('recweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            dirty_month_list.append(row[2])
        line_count += 1
        
dirty_month_list

['11',
 'May',
 '5',
 'Dec',
 'Sep',
 'March',
 '11',
 'Aug',
 'July',
 '9',
 'December',
 '5',
 'January',
 '1',
 '6',
 '4',
 '1',
 'Apr',
 '12',
 '3',
 '7',
 '9',
 '4',
 'Oct',
 '5',
 '12',
 'March',
 '11',
 '10',
 'May',
 '4',
 'Jul',
 '12',
 'Oct',
 '7',
 'December',
 '2',
 '8',
 'May',
 '2',
 'Nov',
 'September',
 'Jan',
 'February',
 'January',
 'Dec',
 'August',
 'Apr',
 '10',
 'March',
 '8',
 '3',
 'Dec',
 '7',
 'May',
 '9',
 'May',
 'April',
 'April',
 'August',
 '9',
 'Dec',
 'Feb',
 'November',
 'Mar',
 'September',
 'Dec',
 'November',
 'November',
 'May',
 '8',
 'December',
 'Jun',
 'Oct',
 'Sep',
 '2',
 'May',
 '9',
 'December',
 '8',
 'Feb',
 '11',
 'Jun',
 'February',
 'Jan',
 'Nov',
 'August',
 'January',
 '3',
 'Mar',
 'Aug',
 'Dec',
 'Jun',
 'November',
 '9',
 'Mar',
 'Jan',
 'Jan',
 'May',
 '5',
 'April',
 'August',
 'Dec',
 'July',
 'Mar',
 '8',
 'April',
 'May',
 '8',
 'January',
 '12',
 'May',
 'May',
 'August',
 'March',
 'Jul',
 '1',
 'Feb',
 'Dec',
 '2',
 '3',

In [21]:
# identifying unique month names

unique_month = set(dirty_month_list)

unique_month

{'1',
 '10',
 '11',
 '12',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'Apr',
 'April',
 'Aug',
 'August',
 'Dec',
 'December',
 'Feb',
 'February',
 'Jan',
 'January',
 'Jul',
 'July',
 'Jun',
 'June',
 'Mar',
 'March',
 'May',
 'Nov',
 'November',
 'Oct',
 'Sep',
 'September'}

In [22]:
# making month dictionary

unique_month_dictionary = {month:None for month in unique_month}

unique_month_dictionary

{'Nov': None,
 'December': None,
 'July': None,
 'April': None,
 '12': None,
 'January': None,
 '5': None,
 'March': None,
 '6': None,
 'May': None,
 'September': None,
 'Apr': None,
 'February': None,
 'Jun': None,
 '8': None,
 '11': None,
 'Sep': None,
 '7': None,
 '2': None,
 'Oct': None,
 'June': None,
 'Mar': None,
 'Jan': None,
 'Dec': None,
 '9': None,
 'Jul': None,
 '4': None,
 'August': None,
 '1': None,
 'November': None,
 '3': None,
 'Aug': None,
 'Feb': None,
 '10': None}

In [23]:
numbermonth_dict = {'1':'January','2':'February','3':'March','4':'April','5':'May','6':'June','7':'July','8':'August','9':'September','10':'October','11':'November','12':'December'}

numbermonth_dict

{'1': 'January',
 '2': 'February',
 '3': 'March',
 '4': 'April',
 '5': 'May',
 '6': 'June',
 '7': 'July',
 '8': 'August',
 '9': 'September',
 '10': 'October',
 '11': 'November',
 '12': 'December'}

In [24]:
shortmonth_dict = {'Jan':'January','Feb':'February','Mar':'March','Apr':'April','May':'May','Jun':'June','Jul':'July','Aug':'August','Sep':'September','Oct':'October','Nov':'November','Dec':'December'}

shortmonth_dict

{'Jan': 'January',
 'Feb': 'February',
 'Mar': 'March',
 'Apr': 'April',
 'May': 'May',
 'Jun': 'June',
 'Jul': 'July',
 'Aug': 'August',
 'Sep': 'September',
 'Oct': 'October',
 'Nov': 'November',
 'Dec': 'December'}

In [26]:
# changing dirty month names to proper/clean month names

for i in unique_month_dictionary:
    if len(i) == 3: # example: Jan, Feb, Mar
        final_month = shortmonth_dict[i]
    elif len(i) < 3: # example: 1, 2, 3
        final_month = numbermonth_dict[i]
    else:
        final_month = i
    unique_month_dictionary[i] = final_month

In [27]:
# creating new list for months with clean month list

clean_month_list = [re.sub(r''.join(month),r''.join(unique_month_dictionary[month]),month) for month in dirty_month_list]

clean_month_list

['November',
 'May',
 'May',
 'December',
 'September',
 'March',
 'November',
 'August',
 'July',
 'September',
 'December',
 'May',
 'January',
 'January',
 'June',
 'April',
 'January',
 'April',
 'December',
 'March',
 'July',
 'September',
 'April',
 'October',
 'May',
 'December',
 'March',
 'November',
 'October',
 'May',
 'April',
 'July',
 'December',
 'October',
 'July',
 'December',
 'February',
 'August',
 'May',
 'February',
 'November',
 'September',
 'January',
 'February',
 'January',
 'December',
 'August',
 'April',
 'October',
 'March',
 'August',
 'March',
 'December',
 'July',
 'May',
 'September',
 'May',
 'April',
 'April',
 'August',
 'September',
 'December',
 'February',
 'November',
 'March',
 'September',
 'December',
 'November',
 'November',
 'May',
 'August',
 'December',
 'June',
 'October',
 'September',
 'February',
 'May',
 'September',
 'December',
 'August',
 'February',
 'November',
 'June',
 'February',
 'January',
 'November',
 'August',
 'Januar

In [28]:
# extracting dirty list of phone numbers

import csv

dirty_phone_list = list()

with open('recweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            dirty_phone_list.append(row[6])
        line_count += 1
        
dirty_phone_list

['+63 918 302 6210',
 '927 212 6276',
 '+63 918 253 7017',
 '918 714 4360',
 '+63 927 462 1674',
 '+63 918 629 5268',
 '+63 917 369 7388',
 '917 240 6000',
 '918 226 5748',
 '+63 918 342 1717',
 '+63 927 708 1308',
 '927 747 5497',
 '+63 917 959 4490',
 '+63 927 543 4192',
 '917 211 9497',
 '+63 918 185 5162',
 '927 146 8146',
 '927 516 4280',
 '+63 927 958 6909',
 '+63 917 514 9105',
 '+63 927 984 7499',
 '+63 927 699 3694',
 '917 317 2478',
 '+63 917 159 3829',
 '+63 918 898 6972',
 '917 796 4622',
 '+63 927 138 7580',
 '+63 917 195 9244',
 '+63 917 643 3996',
 '917 758 3119',
 '+63 918 669 4265',
 '+63 917 750 8539',
 '927 236 9504',
 '917 438 4447',
 '+63 917 773 6035',
 '918 455 4185',
 '927 889 9252',
 '927 874 8083',
 '927 842 3053',
 '927 923 1234',
 '+63 918 381 4956',
 '+63 918 602 9278',
 '+63 918 532 6748',
 '917 654 1291',
 '918 244 1683',
 '917 818 1190',
 '+63 917 468 6425',
 '+63 918 635 1688',
 '917 821 1896',
 '927 924 9506',
 '918 854 2626',
 '+63 918 438 9745',
 '91

In [29]:
# changing dirty phone number to proper/clean phone number

clean_phone_list = []

for number in dirty_phone_list:
    if len(number) == 16: # example: +63 999 999 9999 = len of example is 16
        clean_phone_list.append(number)
    else: # example: 999 999 9999
        newnumber = "+63 " + number # add "+63 " at the start of the number to have a similar format as previous example
        clean_phone_list.append(newnumber)
        
clean_phone_list

['+63 918 302 6210',
 '+63 927 212 6276',
 '+63 918 253 7017',
 '+63 918 714 4360',
 '+63 927 462 1674',
 '+63 918 629 5268',
 '+63 917 369 7388',
 '+63 917 240 6000',
 '+63 918 226 5748',
 '+63 918 342 1717',
 '+63 927 708 1308',
 '+63 927 747 5497',
 '+63 917 959 4490',
 '+63 927 543 4192',
 '+63 917 211 9497',
 '+63 918 185 5162',
 '+63 927 146 8146',
 '+63 927 516 4280',
 '+63 927 958 6909',
 '+63 917 514 9105',
 '+63 927 984 7499',
 '+63 927 699 3694',
 '+63 917 317 2478',
 '+63 917 159 3829',
 '+63 918 898 6972',
 '+63 917 796 4622',
 '+63 927 138 7580',
 '+63 917 195 9244',
 '+63 917 643 3996',
 '+63 917 758 3119',
 '+63 918 669 4265',
 '+63 917 750 8539',
 '+63 927 236 9504',
 '+63 917 438 4447',
 '+63 917 773 6035',
 '+63 918 455 4185',
 '+63 927 889 9252',
 '+63 927 874 8083',
 '+63 927 842 3053',
 '+63 927 923 1234',
 '+63 918 381 4956',
 '+63 918 602 9278',
 '+63 918 532 6748',
 '+63 917 654 1291',
 '+63 918 244 1683',
 '+63 917 818 1190',
 '+63 917 468 6425',
 '+63 918 635

In [30]:
# creating new list for phone number with clean phone number list

clean_number_list = []

for number in clean_phone_list:
    new = number.replace(" ","") # removes spaces
    clean_number_list.append(new)
    
clean_number_list

['+639183026210',
 '+639272126276',
 '+639182537017',
 '+639187144360',
 '+639274621674',
 '+639186295268',
 '+639173697388',
 '+639172406000',
 '+639182265748',
 '+639183421717',
 '+639277081308',
 '+639277475497',
 '+639179594490',
 '+639275434192',
 '+639172119497',
 '+639181855162',
 '+639271468146',
 '+639275164280',
 '+639279586909',
 '+639175149105',
 '+639279847499',
 '+639276993694',
 '+639173172478',
 '+639171593829',
 '+639188986972',
 '+639177964622',
 '+639271387580',
 '+639171959244',
 '+639176433996',
 '+639177583119',
 '+639186694265',
 '+639177508539',
 '+639272369504',
 '+639174384447',
 '+639177736035',
 '+639184554185',
 '+639278899252',
 '+639278748083',
 '+639278423053',
 '+639279231234',
 '+639183814956',
 '+639186029278',
 '+639185326748',
 '+639176541291',
 '+639182441683',
 '+639178181190',
 '+639174686425',
 '+639186351688',
 '+639178211896',
 '+639279249506',
 '+639188542626',
 '+639184389745',
 '+639178938235',
 '+639182165250',
 '+639172571057',
 '+6392794

In [31]:
# extracting first name list

import csv

firstname_list = list()

with open('recweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            firstname_list.append(row[0])
        line_count += 1
        
firstname_list

['name1',
 'name2',
 'name3',
 'name4',
 'name5',
 'name6',
 'name7',
 'name8',
 'name9',
 'name10',
 'name11',
 'name12',
 'name13',
 'name14',
 'name15',
 'name16',
 'name17',
 'name18',
 'name19',
 'name20',
 'name21',
 'name22',
 'name23',
 'name24',
 'name25',
 'name26',
 'name27',
 'name28',
 'name29',
 'name30',
 'name31',
 'name32',
 'name33',
 'name34',
 'name35',
 'name36',
 'name37',
 'name38',
 'name39',
 'name40',
 'name41',
 'name42',
 'name43',
 'name44',
 'name45',
 'name46',
 'name47',
 'name48',
 'name49',
 'name50',
 'name51',
 'name52',
 'name53',
 'name54',
 'name55',
 'name56',
 'name57',
 'name58',
 'name59',
 'name60',
 'name61',
 'name62',
 'name63',
 'name64',
 'name65',
 'name66',
 'name67',
 'name68',
 'name69',
 'name70',
 'name71',
 'name72',
 'name73',
 'name74',
 'name75',
 'name76',
 'name77',
 'name78',
 'name79',
 'name80',
 'name81',
 'name82',
 'name83',
 'name84',
 'name85',
 'name86',
 'name87',
 'name88',
 'name89',
 'name90',
 'name91',
 'name92

In [32]:
# extracting last name list

import csv

lastname_list = list()

with open('recweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            lastname_list.append(row[1])
        line_count += 1
        
lastname_list

['lastname1',
 'lastname2',
 'lastname3',
 'lastname4',
 'lastname5',
 'lastname6',
 'lastname7',
 'lastname8',
 'lastname9',
 'lastname10',
 'lastname11',
 'lastname12',
 'lastname13',
 'lastname14',
 'lastname15',
 'lastname16',
 'lastname17',
 'lastname18',
 'lastname19',
 'lastname20',
 'lastname21',
 'lastname22',
 'lastname23',
 'lastname24',
 'lastname25',
 'lastname26',
 'lastname27',
 'lastname28',
 'lastname29',
 'lastname30',
 'lastname31',
 'lastname32',
 'lastname33',
 'lastname34',
 'lastname35',
 'lastname36',
 'lastname37',
 'lastname38',
 'lastname39',
 'lastname40',
 'lastname41',
 'lastname42',
 'lastname43',
 'lastname44',
 'lastname45',
 'lastname46',
 'lastname47',
 'lastname48',
 'lastname49',
 'lastname50',
 'lastname51',
 'lastname52',
 'lastname53',
 'lastname54',
 'lastname55',
 'lastname56',
 'lastname57',
 'lastname58',
 'lastname59',
 'lastname60',
 'lastname61',
 'lastname62',
 'lastname63',
 'lastname64',
 'lastname65',
 'lastname66',
 'lastname67',
 'la

In [33]:
# extracting day list

import csv

day_list = list()

with open('recweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            day_list.append(row[3])
        line_count += 1
        
day_list

['26',
 '26',
 '16',
 '9',
 '5',
 '2',
 '10',
 '28',
 '10',
 '14',
 '8',
 '4',
 '28',
 '11',
 '6',
 '20',
 '3',
 '8',
 '28',
 '10',
 '13',
 '15',
 '15',
 '1',
 '6',
 '5',
 '4',
 '10',
 '10',
 '28',
 '6',
 '16',
 '17',
 '4',
 '14',
 '11',
 '2',
 '25',
 '3',
 '27',
 '16',
 '24',
 '13',
 '25',
 '27',
 '24',
 '23',
 '13',
 '11',
 '25',
 '22',
 '21',
 '15',
 '10',
 '8',
 '9',
 '9',
 '6',
 '24',
 '26',
 '8',
 '7',
 '22',
 '13',
 '23',
 '24',
 '9',
 '4',
 '19',
 '12',
 '19',
 '1',
 '21',
 '25',
 '17',
 '2',
 '19',
 '15',
 '23',
 '10',
 '1',
 '22',
 '18',
 '28',
 '10',
 '21',
 '15',
 '26',
 '26',
 '15',
 '16',
 '8',
 '14',
 '24',
 '6',
 '16',
 '19',
 '10',
 '12',
 '10',
 '2',
 '14',
 '16',
 '16',
 '5',
 '25',
 '21',
 '14',
 '15',
 '8',
 '22',
 '19',
 '27',
 '22',
 '26',
 '19',
 '11',
 '4',
 '27',
 '3',
 '5',
 '1',
 '23',
 '2',
 '24',
 '4',
 '3',
 '20',
 '25',
 '18',
 '23',
 '10',
 '18',
 '7',
 '3',
 '5',
 '5',
 '5',
 '8',
 '2',
 '8',
 '3',
 '15',
 '14',
 '9',
 '11',
 '6',
 '13',
 '18',
 '5',
 

In [34]:
# this is what you will see in the new clean csv file
# practice

print('firstname,'+'lastname,'+'birthmonth,'+'birthday,'+'birthyear,'+'course,'+'phonenumber')
for i in range(len(firstname_list)+1):
    print(firstname_list[i]+","+lastname_list[i]+","+clean_month_list[i]+","+day_list[i]+","+clean_year_list[i]+","+clean_course_list[i]+","+clean_number_list[i])

firstname,lastname,birthmonth,birthday,birthyear,course,phonenumber
name1,lastname1,November,26,98,BS Legal Management,+639183026210
name2,lastname2,May,26,01,BS Management,+639272126276
name3,lastname3,May,16,97,BS Communications Technology Management,+639182537017
name4,lastname4,December,9,97,BS Information Technology Entrepreneurship,+639187144360
name5,lastname5,September,5,97,BS Communications Technology Management,+639274621674
name6,lastname6,March,2,99,BS Management,+639186295268
name7,lastname7,November,10,98,BS Legal Management,+639173697388
name8,lastname8,August,28,99,BS Management Engineering,+639172406000
name9,lastname9,July,10,97,BS Management Engineering,+639182265748
name10,lastname10,September,14,01,BS Communications Technology Management,+639183421717
name11,lastname11,December,8,98,BS Legal Management,+639277081308
name12,lastname12,May,4,97,BS Management Engineering,+639277475497
name13,lastname13,January,28,99,BS Communications Technology Management,+63917959449

name1487,lastname1487,February,6,00,BS Management Engineering,+639177744619
name1488,lastname1488,May,8,98,BS Management Engineering,+639179821304
name1489,lastname1489,August,25,98,BS Legal Management,+639184664113
name1490,lastname1490,November,15,99,BS Management Engineering,+639275264600
name1491,lastname1491,November,19,97,BS Management,+639178405589
name1492,lastname1492,March,4,99,BS Communications Technology Management,+639183373436
name1493,lastname1493,September,17,01,BS Management,+639188508278
name1494,lastname1494,June,2,99,BS Information Technology Entrepreneurship,+639272722481
name1495,lastname1495,May,1,97,BS Communications Technology Management,+639273178513
name1496,lastname1496,April,1,98,BS Management,+639174722973
name1497,lastname1497,November,4,97,BS Information Technology Entrepreneurship,+639279792316
name1498,lastname1498,April,27,97,BS Communications Technology Management,+639278721565
name1499,lastname1499,September,13,01,BS Legal Management,+639278993998
n

IndexError: list index out of range

In [61]:
# final
# use zip to concatenate corresponding information (first name, last name, birth month, birth day, birth year, course, phone number) for each person
# will end up with the same format as the practice above

rows = zip(firstname_list,lastname_list,clean_month_list,day_list,clean_year_list,clean_course_list,clean_number_list)

In [62]:
# creating a new csv file containing clean list

import csv

with open('cleanrecweekdata.csv', 'a', newline='') as csvfile:
    order_writer = csv.writer(csvfile, quoting=csv.QUOTE_MINIMAL)
    order_writer.writerow(["firstname","lastname","birthmonth","birthday","birthyear","course","phonenumber"])
    for row in rows:
        order_writer.writerow(row)

# Required Summary Statistics
1. How many people were born in each month?
2. How many people were born on each day?
3. How many people were born in each year?
4. How many people come from each course?
5. How many people have numbers from Globe (0917 or 0927) and Smart (0918)? *Note: it's up to you how to format this output*

Answer these questions in an html file called stats.html. The format of the html is as follows (in template form, so you can use this as format string in your program, though feel free to modify with variable names if you find it easier to do so):


```
<html>
    <body>
         <h2>Summary Statistics</h2>
         <table>
             <tr><th>Stat</th><th>Value</th></tr>
             <tr><td>People born in each month</td><td>{}</td></tr>
             <tr><td>People born on each day</td><td>{}</td></tr>
             <tr><td>People born in each year</td><td>{}</td></tr>
             <tr><td>People coming from each course</td><td>{}</td></tr>
             <tr><td>People having numbers from Globe and Smart</td><td>{}</td></tr>
         </table>
    </body>
</html>
```

In [63]:
# extracting months from clean list

import csv

month = list()

with open('cleanrecweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            month.append(row[2])
        line_count += 1
        
month

['November',
 'May',
 'May',
 'December',
 'September',
 'March',
 'November',
 'August',
 'July',
 'September',
 'December',
 'May',
 'January',
 'January',
 'June',
 'April',
 'January',
 'April',
 'December',
 'March',
 'July',
 'September',
 'April',
 'October',
 'May',
 'December',
 'March',
 'November',
 'October',
 'May',
 'April',
 'July',
 'December',
 'October',
 'July',
 'December',
 'February',
 'August',
 'May',
 'February',
 'November',
 'September',
 'January',
 'February',
 'January',
 'December',
 'August',
 'April',
 'October',
 'March',
 'August',
 'March',
 'December',
 'July',
 'May',
 'September',
 'May',
 'April',
 'April',
 'August',
 'September',
 'December',
 'February',
 'November',
 'March',
 'September',
 'December',
 'November',
 'November',
 'May',
 'August',
 'December',
 'June',
 'October',
 'September',
 'February',
 'May',
 'September',
 'December',
 'August',
 'February',
 'November',
 'June',
 'February',
 'January',
 'November',
 'August',
 'Januar

In [64]:
month_list = month

month_tally = {}

# identify unique months
month_set = set(month_list)

# set counter to 0
for month in month_set:
    month_tally[month] = 0

# counts how many for each month
for month in month_list:
    month_tally[month] += 1
    
month_tally

{'June': 259,
 'February': 232,
 'December': 276,
 'November': 277,
 'July': 249,
 'April': 267,
 'January': 270,
 'August': 241,
 'October': 178,
 'March': 246,
 'May': 273,
 'September': 232}

In [65]:
# extracting days from clean list

import csv

day = list()

with open('cleanrecweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            day.append(row[3])
        line_count += 1
        
day

['26',
 '26',
 '16',
 '9',
 '5',
 '2',
 '10',
 '28',
 '10',
 '14',
 '8',
 '4',
 '28',
 '11',
 '6',
 '20',
 '3',
 '8',
 '28',
 '10',
 '13',
 '15',
 '15',
 '1',
 '6',
 '5',
 '4',
 '10',
 '10',
 '28',
 '6',
 '16',
 '17',
 '4',
 '14',
 '11',
 '2',
 '25',
 '3',
 '27',
 '16',
 '24',
 '13',
 '25',
 '27',
 '24',
 '23',
 '13',
 '11',
 '25',
 '22',
 '21',
 '15',
 '10',
 '8',
 '9',
 '9',
 '6',
 '24',
 '26',
 '8',
 '7',
 '22',
 '13',
 '23',
 '24',
 '9',
 '4',
 '19',
 '12',
 '19',
 '1',
 '21',
 '25',
 '17',
 '2',
 '19',
 '15',
 '23',
 '10',
 '1',
 '22',
 '18',
 '28',
 '10',
 '21',
 '15',
 '26',
 '26',
 '15',
 '16',
 '8',
 '14',
 '24',
 '6',
 '16',
 '19',
 '10',
 '12',
 '10',
 '2',
 '14',
 '16',
 '16',
 '5',
 '25',
 '21',
 '14',
 '15',
 '8',
 '22',
 '19',
 '27',
 '22',
 '26',
 '19',
 '11',
 '4',
 '27',
 '3',
 '5',
 '1',
 '23',
 '2',
 '24',
 '4',
 '3',
 '20',
 '25',
 '18',
 '23',
 '10',
 '18',
 '7',
 '3',
 '5',
 '5',
 '5',
 '8',
 '2',
 '8',
 '3',
 '15',
 '14',
 '9',
 '11',
 '6',
 '13',
 '18',
 '5',
 

In [66]:
day_list = day

day_tally = {}

# identify unique days
day_set = set(day_list)

# set counter to 0
for day in day_set:
    day_tally[day] = 0

# counts how many for each day
for day in day_list:
    day_tally[day] += 1
    
day_tally

{'28': 104,
 '12': 98,
 '24': 108,
 '5': 100,
 '27': 102,
 '6': 99,
 '8': 111,
 '11': 105,
 '2': 106,
 '7': 88,
 '20': 91,
 '9': 98,
 '19': 113,
 '4': 110,
 '22': 103,
 '1': 112,
 '14': 102,
 '17': 116,
 '3': 90,
 '16': 115,
 '13': 119,
 '21': 123,
 '10': 111,
 '26': 116,
 '23': 116,
 '15': 121,
 '18': 107,
 '25': 116}

In [67]:
# extracting years from clean list

import csv

year = list()

with open('cleanrecweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            year.append(row[4])
        line_count += 1
        
year

['98',
 '01',
 '97',
 '97',
 '97',
 '99',
 '98',
 '99',
 '97',
 '01',
 '98',
 '97',
 '99',
 '99',
 '98',
 '99',
 '97',
 '97',
 '97',
 '97',
 '99',
 '99',
 '97',
 '97',
 '97',
 '99',
 '97',
 '00',
 '99',
 '99',
 '99',
 '99',
 '99',
 '99',
 '01',
 '98',
 '00',
 '01',
 '97',
 '98',
 '99',
 '98',
 '99',
 '98',
 '97',
 '98',
 '99',
 '99',
 '97',
 '01',
 '98',
 '99',
 '00',
 '98',
 '98',
 '98',
 '01',
 '97',
 '98',
 '99',
 '98',
 '00',
 '00',
 '97',
 '97',
 '97',
 '97',
 '01',
 '98',
 '98',
 '99',
 '99',
 '98',
 '97',
 '98',
 '97',
 '00',
 '00',
 '00',
 '99',
 '97',
 '97',
 '00',
 '99',
 '99',
 '98',
 '98',
 '97',
 '98',
 '99',
 '97',
 '97',
 '98',
 '97',
 '01',
 '99',
 '97',
 '98',
 '98',
 '99',
 '97',
 '01',
 '00',
 '01',
 '99',
 '97',
 '01',
 '99',
 '98',
 '99',
 '01',
 '97',
 '97',
 '99',
 '98',
 '97',
 '97',
 '99',
 '97',
 '97',
 '00',
 '01',
 '99',
 '99',
 '98',
 '00',
 '00',
 '98',
 '98',
 '00',
 '99',
 '99',
 '99',
 '00',
 '99',
 '00',
 '98',
 '97',
 '99',
 '99',
 '98',
 '99',
 '99',

In [68]:
year_list = year

year_tally = {}

# identify unique years
year_set = set(year_list)

# set counter to 0
for year in year_set:
    year_tally[year] = 0

# counts how many for each year
for year in year_list:
    year_tally[year] += 1
    
year_tally

{'01': 362, '98': 746, '97': 756, '99': 756, '00': 380}

In [69]:
# extracting courses from clean list

import csv

course = list()

with open('cleanrecweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            course.append(row[5])
        line_count += 1
        
course

['BS Legal Management',
 'BS Management',
 'BS Communications Technology Management',
 'BS Information Technology Entrepreneurship',
 'BS Communications Technology Management',
 'BS Management',
 'BS Legal Management',
 'BS Management Engineering',
 'BS Management Engineering',
 'BS Communications Technology Management',
 'BS Legal Management',
 'BS Management Engineering',
 'BS Communications Technology Management',
 'BS Management',
 'BS Information Technology Entrepreneurship',
 'BS Legal Management',
 'BS Information Technology Entrepreneurship',
 'BS Management',
 'BS Information Technology Entrepreneurship',
 'BS Management Engineering',
 'BS Legal Management',
 'BS Information Technology Entrepreneurship',
 'BS Management',
 'BS Management Engineering',
 'BS Management Engineering',
 'BS Management Engineering',
 'BS Communications Technology Management',
 'BS Legal Management',
 'BS Legal Management',
 'BS Communications Technology Management',
 'BS Information Technology Entre

In [70]:
course_list = course

course_tally = {}

# identify unique courses
course_set = set(course_list)

# set counter to 0
for course in course_set:
    course_tally[course] = 0

# counts how many for each course
for course in course_list:
    course_tally[course] += 1
    
course_tally

{'BS Legal Management': 585,
 'BS Information Technology Entrepreneurship': 590,
 'BS Management Engineering': 607,
 'BS Communications Technology Management': 589,
 'BS Management': 629}

In [71]:
# extracting phone number from clean list

import csv

phone_number = list()

with open('cleanrecweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            pass
        else:
            phone_number.append(row[6])
        line_count += 1
        
phone_number

['+639183026210',
 '+639272126276',
 '+639182537017',
 '+639187144360',
 '+639274621674',
 '+639186295268',
 '+639173697388',
 '+639172406000',
 '+639182265748',
 '+639183421717',
 '+639277081308',
 '+639277475497',
 '+639179594490',
 '+639275434192',
 '+639172119497',
 '+639181855162',
 '+639271468146',
 '+639275164280',
 '+639279586909',
 '+639175149105',
 '+639279847499',
 '+639276993694',
 '+639173172478',
 '+639171593829',
 '+639188986972',
 '+639177964622',
 '+639271387580',
 '+639171959244',
 '+639176433996',
 '+639177583119',
 '+639186694265',
 '+639177508539',
 '+639272369504',
 '+639174384447',
 '+639177736035',
 '+639184554185',
 '+639278899252',
 '+639278748083',
 '+639278423053',
 '+639279231234',
 '+639183814956',
 '+639186029278',
 '+639185326748',
 '+639176541291',
 '+639182441683',
 '+639178181190',
 '+639174686425',
 '+639186351688',
 '+639178211896',
 '+639279249506',
 '+639188542626',
 '+639184389745',
 '+639178938235',
 '+639182165250',
 '+639172571057',
 '+6392794

In [72]:
# get the 3rd, 4th, and 5th digits of each number and make a new list
# this will determine whether the number is globe or smart

phone_list = []
for phone in phone_number:
    phone_list.append(phone[3:6])
    
phone_list

['918',
 '927',
 '918',
 '918',
 '927',
 '918',
 '917',
 '917',
 '918',
 '918',
 '927',
 '927',
 '917',
 '927',
 '917',
 '918',
 '927',
 '927',
 '927',
 '917',
 '927',
 '927',
 '917',
 '917',
 '918',
 '917',
 '927',
 '917',
 '917',
 '917',
 '918',
 '917',
 '927',
 '917',
 '917',
 '918',
 '927',
 '927',
 '927',
 '927',
 '918',
 '918',
 '918',
 '917',
 '918',
 '917',
 '917',
 '918',
 '917',
 '927',
 '918',
 '918',
 '917',
 '918',
 '917',
 '927',
 '927',
 '918',
 '917',
 '918',
 '918',
 '927',
 '918',
 '917',
 '927',
 '917',
 '917',
 '927',
 '917',
 '917',
 '918',
 '927',
 '918',
 '927',
 '927',
 '927',
 '918',
 '918',
 '927',
 '927',
 '918',
 '918',
 '927',
 '917',
 '927',
 '918',
 '918',
 '917',
 '917',
 '918',
 '918',
 '917',
 '927',
 '918',
 '927',
 '917',
 '918',
 '927',
 '927',
 '927',
 '927',
 '918',
 '927',
 '918',
 '917',
 '927',
 '927',
 '918',
 '917',
 '918',
 '918',
 '918',
 '917',
 '917',
 '917',
 '918',
 '918',
 '918',
 '927',
 '918',
 '918',
 '917',
 '918',
 '917',
 '917',


In [73]:
phone_tally = {}

# identify unique assigned carrier number
phone_set = set(phone_list)

# set counter to 0
for num in phone_set:
    phone_tally[num] = 0

# counts how many for each carrier number
for num in phone_list:
    phone_tally[num] += 1
    
phone_tally

{'927': 1019, '917': 1026, '918': 955}

# FINAL CSS HTML IS AT THE END OF THIS NOTEBOOK

In [74]:
# INITIAL, RAW HTML

raw_html = """
    <html>
        <body>
             <h2>Summary Statistics</h2>
             <table>
                 <tr><th>People born in each month</th><th>Month</th><th>Count</th></tr>
                 <tr><td></td><td>January</td><td>270</td></tr>
                 <tr><td></td><td>February</td><td>232</td></tr>
                 <tr><td></td><td>March</td><td>246</td></tr>
                 <tr><td></td><td>April</td><td>267</td></tr>
                 <tr><td></td><td>May</td><td>273</td></tr>
                 <tr><td></td><td>June</td><td>259</td></tr>
                 <tr><td></td><td>July</td><td>249</td></tr>
                 <tr><td></td><td>August</td><td>241</td></tr>
                 <tr><td></td><td>September  </td><td>232</td></tr>
                 <tr><td></td><td>October</td><td>178</td></tr>
                 <tr><td></td><td>November</td><td>277</td></tr>
                 <tr><td></td><td>December</td><td>276</td></tr>
                 <tr><td>People born on each day</td><td><b>Day</b></td><td><b>Count</b></td></tr>
                 <tr><td></td><td>1</td><td>112</td></tr>
                 <tr><td></td><td>2</td><td>106</td></tr>
                 <tr><td></td><td>3</td><td>90</td></tr>
                 <tr><td></td><td>4</td><td>110</td></tr>
                 <tr><td></td><td>5</td><td>100</td></tr>
                 <tr><td></td><td>6</td><td>99</td></tr>
                 <tr><td></td><td>7</td><td>88</td></tr>
                 <tr><td></td><td>8</td><td>111</td></tr>
                 <tr><td></td><td>9</td><td>98</td></tr>
                 <tr><td></td><td>10</td><td>111</td></tr>
                 <tr><td></td><td>11</td><td>105</td></tr>
                 <tr><td></td><td>12</td><td>98</td></tr>
                 <tr><td></td><td>13</td><td>119</td></tr>
                 <tr><td></td><td>14</td><td>102</td></tr>
                 <tr><td></td><td>15</td><td>121</td></tr>
                 <tr><td></td><td>16</td><td>115</td></tr>
                 <tr><td></td><td>17</td><td>116</td></tr>
                 <tr><td></td><td>18</td><td>107</td></tr>
                 <tr><td></td><td>19</td><td>113</td></tr>
                 <tr><td></td><td>20</td><td>91</td></tr>
                 <tr><td></td><td>21</td><td>123</td></tr>
                 <tr><td></td><td>22</td><td>103</td></tr>
                 <tr><td></td><td>23</td><td>116</td></tr>
                 <tr><td></td><td>24</td><td>108</td></tr>
                 <tr><td></td><td>25</td><td>116</td></tr>
                 <tr><td></td><td>26</td><td>116</td></tr>
                 <tr><td></td><td>27</td><td>102</td></tr>
                 <tr><td></td><td>28</td><td>104</td></tr>
                 <tr><td>People born in each year</td><td><b>Year</b></td><td><b>Count</b></td></tr>
                 <tr><td></td><td>1997</td><td>756</td></tr>
                 <tr><td></td><td>1998</td><td>746</td></tr>
                 <tr><td></td><td>1999</td><td>756</td></tr>
                 <tr><td></td><td>2000</td><td>380</td></tr>
                 <tr><td></td><td>2001</td><td>362</td></tr>
                 <tr><td>People coming from each course</td><td><b>Course</b></td><td><b>Count</b></td></tr>
                 <tr><td></td><td>BS Communications Technology Management</td><td>589</td></tr>
                 <tr><td></td><td>BS Information Technology Entrepreneurship</td><td>590</td></tr>
                 <tr><td></td><td>BS Legal Management</td><td>585</td></tr>
                 <tr><td></td><td>BS Management</td><td>629</td></tr>
                 <tr><td></td><td>BS Management Engineering</td><td>607</td></tr>
                 <tr><td>People having numbers from Globe and Smart</td><td><b>Carrier</b></td><td><b>Count</b></td></tr>
                 <tr><td></td><td>Globe (0917)</td><td>1026</td></tr>
                 <tr><td></td><td>Globe (0927)</td><td>1019</td></tr>
                 <tr><td></td><td>Globe (Total)</td><td>2045</td></tr>
                 <tr><td></td><td>Smart (0918)</td><td>955</td></tr>
             </table>
        </body>
    </html>
"""

with open('statsraw.html',"w+") as file:
    file.write(raw_html)

# PRETTY CSS VERSION

In [78]:
styledhtml = """
    <html>
        <head>
            <link rel="stylesheet" type="css" href="statsstyled.css" />
        </head>
        <body>
            <div id="Font1"><div id="text1">Summary Statistics</div></div>
            <h2></h2>
            <div id="Font2">people born in each month</div>
            <div class="divTable Kirsten2">
            <div class="divTableHeading">
            <div class="divTableRow">
            <div class="divTableHead">Month</div>
            <div class="divTableHead">Count</div>
            </div>
            </div>
            <div class="divTableBody">
            <div class="divTableRow">
            <div class="divTableCell">January</div>
            <div class="divTableCell">270</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">February</div>
            <div class="divTableCell">232</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">March</div>
            <div class="divTableCell">246</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">April</div>
            <div class="divTableCell">267</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">May</div>
            <div class="divTableCell">273</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">June</div>
            <div class="divTableCell">259</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">July</div>
            <div class="divTableCell">249</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">August</div>
            <div class="divTableCell">241</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">September</div>
            <div class="divTableCell">232</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">October</div>
            <div class="divTableCell">178</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">November</div>
            <div class="divTableCell">277</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">December</div>
            <div class="divTableCell">276</div>
            </div>
            </div>
            </div>
            <h2></h2>
            <div id="Font2">people born on each day</div>
            <div class="divTable Kirsten2">
            <div class="divTableHeading">
            <div class="divTableRow">
            <div class="divTableHead">Day</div>
            <div class="divTableHead">Count</div>
            </div>
            </div>
            <div class="divTableBody">
            <div class="divTableRow">
            <div class="divTableCell">1</div>
            <div class="divTableCell">112</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">2</div>
            <div class="divTableCell">106</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">3</div>
            <div class="divTableCell">90</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">4</div>
            <div class="divTableCell">110</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">5</div>
            <div class="divTableCell">100</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">6</div>
            <div class="divTableCell">99</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">7</div>
            <div class="divTableCell">88</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">8</div>
            <div class="divTableCell">111</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">9</div>
            <div class="divTableCell">98</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">10</div>
            <div class="divTableCell">111</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">11</div>
            <div class="divTableCell">105</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">12</div>
            <div class="divTableCell">98</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">13</div>
            <div class="divTableCell">119</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">14</div>
            <div class="divTableCell">102</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">15</div>
            <div class="divTableCell">121</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">16</div>
            <div class="divTableCell">115</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">17</div>
            <div class="divTableCell">116</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">18</div>
            <div class="divTableCell">107</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">19</div>
            <div class="divTableCell">113</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">20</div>
            <div class="divTableCell">91</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">21</div>
            <div class="divTableCell">123</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">22</div>
            <div class="divTableCell">103</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">23</div>
            <div class="divTableCell">116</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">24</div>
            <div class="divTableCell">108</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">25</div>
            <div class="divTableCell">116</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">26</div>
            <div class="divTableCell">116</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">27</div>
            <div class="divTableCell">102</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">28</div>
            <div class="divTableCell">104</div>
            </div>
            </div>
            </div>
            <h2></h2>
            <div id="Font2">people born in each year</div>
            <div class="divTable Kirsten2">
            <div class="divTableHeading">
            <div class="divTableRow">
            <div class="divTableHead">Year</div>
            <div class="divTableHead">Count</div>
            </div>
            </div>
            <div class="divTableBody">
            <div class="divTableRow">
            <div class="divTableCell">1997</div>
            <div class="divTableCell">756</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">1998</div>
            <div class="divTableCell">746</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">1999</div>
            <div class="divTableCell">756</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">2000</div>
            <div class="divTableCell">380</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">2001</div>
            <div class="divTableCell">362</div>
            </div>
            </div>
            </div>
            <h2></h2>
            <div id="Font2">people coming from each course</div>
            <div class="divTable Kirsten2">
            <div class="divTableHeading">
            <div class="divTableRow">
            <div class="divTableHead">Course</div>
            <div class="divTableHead">Count</div>
            </div>
            </div>
            <div class="divTableBody">
            <div class="divTableRow">
            <div class="divTableCell">BS Communications Technology Management</div>
            <div class="divTableCell">589</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">BS Information Technology Entrepreneurship</div>
            <div class="divTableCell">590</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">BS Legal Management</div>
            <div class="divTableCell">585</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">BS Management</div>
            <div class="divTableCell">629</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">BS Management Engineering</div>
            <div class="divTableCell">607</div>
            </div>
            </div>
            </div>
            <h2></h2>
            <div id="Font2">people having numbers from globe and smart</div>
            <div class="divTable Kirsten2">
            <div class="divTableHeading">
            <div class="divTableRow">
            <div class="divTableHead">Globe (0917 and 0927)</div>
            <div class="divTableHead">Count</div>
            </div>
            </div>
            <div class="divTableBody">
            <div class="divTableRow">
            <div class="divTableCell">(0917)</div>
            <div class="divTableCell">1026</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell">(0927)</div>
            <div class="divTableCell">1019</div>
            </div>
            <div class="divTableRow">
            <div class="divTableCell"><b>TOTAL</b></div>
            <div class="divTableCell"><b>2045</b></div>
            </div>
            </div>
            </div>
            <h4></h4>
            <div class="divTable Kirsten2">
            <div class="divTableHeading">
            <div class="divTableRow">
            <div class="divTableHead">Smart (0918)</div>
            <div class="divTableHead">Count</div>
            </div>
            </div>
            <div class="divTableBody">
            <div class="divTableRow">
            <div class="divTableCell"><b>TOTAL</b></div>
            <div class="divTableCell"><b>955</b></div>
            </div>
            </div>
            </div>
        </body>
    </html>
"""

with open('statsstyled.html',"w+") as file:
    file.write(styledhtml)

# FINAL HTML CODE

In [76]:
htmlfinal = """
    <html>
        <head>
            <link rel="stylesheet" type="css" href="test.css" />
        </head>
        <body>
            <div class="container">
                <div class="conta">
                    <div class="bl-main" id="bl-main">
                        <section>
                            <div class="bl-box">
                                <h2>MONTH</h2>
                                <div class="divTable Kirsten1">
                                <div class="divTableHeading">
                                <div class="divTableRow">
                                <div class="divTableHead">Month</div>
                                <div class="divTableHead">Count</div>
                                </div>
                                </div>
                                <div class="divTableBody">
                                <div class="divTableRow">
                                <div class="divTableCell">January</div>
                                <div class="divTableCell">270</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">February</div>
                                <div class="divTableCell">232</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">March</div>
                                <div class="divTableCell">246</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">April</div>
                                <div class="divTableCell">267</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">May</div>
                                <div class="divTableCell">273</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">June</div>
                                <div class="divTableCell">259</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">July</div>
                                <div class="divTableCell">249</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">August</div>
                                <div class="divTableCell">241</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">September</div>
                                <div class="divTableCell">232</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">October</div>
                                <div class="divTableCell">178</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">November</div>
                                <div class="divTableCell">277</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">December</div>
                                <div class="divTableCell">276</div>
                                </div>
                                </div>
                                </div>
                            </div>
                        </section>

                        <section>
                            <div class="bl-box">
                                <h2>DAY</h2>
                                <div class="divTable Kirsten1">
                                <div class="divTableHeading">
                                <div class="divTableRow">
                                <div class="divTableHead">Day</div>
                                <div class="divTableHead">Count</div>
                                </div>
                                </div>
                                <div class="divTableBody">
                                <div class="divTableRow">
                                <div class="divTableCell">1</div>
                                <div class="divTableCell">112</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">2</div>
                                <div class="divTableCell">106</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">3</div>
                                <div class="divTableCell">90</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">4</div>
                                <div class="divTableCell">110</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">5</div>
                                <div class="divTableCell">100</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">6</div>
                                <div class="divTableCell">99</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">7</div>
                                <div class="divTableCell">88</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">8</div>
                                <div class="divTableCell">111</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">9</div>
                                <div class="divTableCell">98</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">10</div>
                                <div class="divTableCell">111</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">11</div>
                                <div class="divTableCell">105</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">12</div>
                                <div class="divTableCell">98</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">13</div>
                                <div class="divTableCell">119</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">14</div>
                                <div class="divTableCell">102</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">15</div>
                                <div class="divTableCell">121</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">16</div>
                                <div class="divTableCell">115</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">17</div>
                                <div class="divTableCell">116</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">18</div>
                                <div class="divTableCell">107</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">19</div>
                                <div class="divTableCell">113</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">20</div>
                                <div class="divTableCell">91</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">21</div>
                                <div class="divTableCell">123</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">22</div>
                                <div class="divTableCell">103</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">23</div>
                                <div class="divTableCell">116</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">24</div>
                                <div class="divTableCell">108</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">25</div>
                                <div class="divTableCell">116</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">26</div>
                                <div class="divTableCell">116</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">27</div>
                                <div class="divTableCell">102</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">28</div>
                                <div class="divTableCell">104</div>
                                </div>
                                </div>
                                </div>
                            </div>
                        </section>

                        <section>
                            <div class="bl-box">
                                <h2>YEAR</h2>
                                <div class="divTable Kirsten1">
                                <div class="divTableHeading">
                                <div class="divTableRow">
                                <div class="divTableHead">Year</div>
                                <div class="divTableHead">Count</div>
                                </div>
                                </div>
                                <div class="divTableBody">
                                <div class="divTableRow">
                                <div class="divTableCell">1997</div>
                                <div class="divTableCell">756</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">1998</div>
                                <div class="divTableCell">746</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">1999</div>
                                <div class="divTableCell">756</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">2000</div>
                                <div class="divTableCell">380</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">2001</div>
                                <div class="divTableCell">362</div>
                                </div>
                                </div>
                                </div>
                            </div>
                        </section>

                        <section id="bl-work-section">
                            <div class="bl-box">
                                <h2>COURSE</h2>
                                <div class="divTable Kirsten1">
                                <div class="divTableHeading">
                                <div class="divTableRow">
                                <div class="divTableHead">Course</div>
                                <div class="divTableHead">Count</div>
                                </div>
                                </div>
                                <div class="divTableBody">
                                <div class="divTableRow">
                                <div class="divTableCell">BS Communications Technology Management</div>
                                <div class="divTableCell">589</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">BS Information Technology Entrepreneurship</div>
                                <div class="divTableCell">590</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">BS Legal Management</div>
                                <div class="divTableCell">585</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">BS Management</div>
                                <div class="divTableCell">629</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">BS Management Engineering</div>
                                <div class="divTableCell">607</div>
                                </div>
                                </div>
                                </div>
                            </div>
                        </section>

                        <section>
                            <div class="bl-box">
                                <h2>PHONE NUMBER</h2>
                                <div class="divTable Kirsten1">
                                <div class="divTableHeading">
                                <div class="divTableRow">
                                <div class="divTableHead">Carrier</div>
                                <div class="divTableHead">Count</div>
                                </div>
                                </div>
                                <div class="divTableBody">
                                <div class="divTableRow">
                                <div class="divTableCell">Globe</div>
                                <div class="divTableCell">2045</div>
                                </div>
                                <div class="divTableRow">
                                <div class="divTableCell">Smart</div>
                                <div class="divTableCell">995</div>
                                </div>
                                </div>
                                </div>
                            </div>
                        </section>

                        </div>
                    </div>
                </div>
            </div>
        </body>
    </html>
"""

with open('stats.html',"w+") as file:
    file.write(htmlfinal)